### ISSUE TITLE
feat: add safeguarding

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/covid-tutoring#45]
### Problems
The biggest concern in all nonprofits like this one is safeguarding. How are you going to run background checks on your volunteer tutors? How does one know if their tutor is qualified? Who is liable if something terrible happens between the volunteer tutor and the student **that you connected**?

### Solutions
Our recommended safeguarding flow looks like this:

> Students must enter their parent’s contact info before sending lesson requests. Parents then receive emails for each lesson request with:
> - The tutor’s profile (that the tutor inputs on our site)
> - The tutor’s verified (via an academic email address) university position (e.g. “student at Duke University”)
> - Links to the tutor’s (verified) social accounts (e.g. their LinkedIn, Facebook, Instagram)
> 
> An option to run (and pay for) various background checks (e.g. a state-wide sex-offender lookup or DBS check)
> 
> Note that once a background check has been paid for by one parent, that background check is added to the site and becomes available to everyone at no extra cost.
> 
> Once the parent signs off on a tutor, the student will meet with them via Bramble (no direct contact info is ever shared).
> 
> Parents are also encouraged to join the first tutoring session.

**Comment by nicholaschiang** [comment]
Comment from Emil Lassen (Co-founder and CEO of Project Access International):
> **For the UK:**
> I was surprised myself when I heard about the safeguarding expectations in the UK. A couple of charities really messed up a few years back and since then, it’s been a fundamental requirement. 
> 
> At CTI we work with students who have been sent to us directly from colleges at Cambridge, which they agreed to only because of our safeguarding setup. So while I think both Jacob, I and the rest of the team involved in the initiative like the idea of yours tech, it is a must-have for us to be able to:
> 1. Take all tutors through a safeguarding training (and, hopefully in the near future, a DBS check)
> 2. Record all sessions and allow easy monitoring
> 
> The setup we have now is scalable to the extend we need right now. If you have dev capacity to co-develop/advice us on how to build an architecture around something like Twilio’s video+IM products, I think we’d be keen to discuss and we have the funds to run OPEX. If I remember correctly, Tutorbook also runs on Bramble. While it’s great for tutoring of younger kids, the UX is suboptimal for older students. So we’re open to explore an alternative to this. 

We'll have to implement the above described setup to be able to work with [the UK's CTI](https://coronavirustutoring.co.uk) (and we definitely want to work with them haha).

**Comment by nicholaschiang** [comment]
Now (live in `develop`; can be [previewed here](https://covid-tutoring-git-develop.tutorbook.now.sh)):
1. Pupils create new "pending lesson requests" instead of directly creating appointments.
2. We send an "Approve lesson request" email to the pupil's parent (see below picture).
3. Once the parent approves of the pupil-tutor match (i.e. they're satisfied that the tutor is qualified to tutor their child), we create the tutoring appointment and the tutor and pupil receive instructions for how to access their Bramble room.

Parental approval email (I'm adding the design team to this issue to get feedback):
![image](https://user-images.githubusercontent.com/20798889/82007678-aedb9480-961f-11ea-8446-68259a94e734.png)

**Comment by nicholaschiang** [comment]
Looping in the **#design** team here:

@kryssym and @selinahsu what do you think about that flow? What do you think about the above email?

**Comment by nicholaschiang** [comment]
Finished MVP and documented it [here](http://help.tutorbook.org/en/articles/4048870-how-it-works).

**Comment by kartik918** [comment]
We can hide Github in the email since it isn't exactly a "social" or something that could be used for validation. Plus parents generally don't know much about Github.

**Comment by nicholaschiang** [comment]
Going to address @kartik918's comment.
