### ISSUE TITLE
feat: create landing/about pages

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/covid-tutoring#5]
From @AlephTaw's [original issue](https://github.com/tutorbookapp/tutorbook/issues/260):

> Version 2 Google Slides - Feel free to insert revisions, so we can collab/compare/keep a tight product to UI/UX feedback loop.Thanks!!!
> 
> Pages:
> 
> Landing Page:
> 
> Parents, Students <-> Tutors
> 
> Nav Bar: About, Meet our Team!, Contact, Volunteer, FAQs, Student Resources
> 
> Student Page:
> 
> Layout: Side-by-side - Description | Form
> 
> LogIn or signup - Description of the service … Here’s how we can help you get individualized educational support during the covid -19 … 1) Sign Up 2) … 3) One of our tutors.
> 
> Student Sign-Up:
> Parent, Student:
> Want to learn more about us? Meet our team, visit our FAQs, or contact us.
> Fills out Form (Below):
> Parent Name*
> Parent Phone Number*
> Parent Email*
> Student Name*
> Student Email*
> Grade Level
> City
> State
> Zip
> 
> Student Login:
> -> Student Account: Tutor Portfoliio -> Grid of (Tutors, Subjects) Pairs w/ mini Bios and next appointment (time, day, date in student time zone), a link to their Google Drive Folder (and subfolders (one for each tutor)), ability to submit a rating: 1-5 stars + text field to submit reviews, I would like to report an issue (checkbox), to tutor records [submit], button for canceling an appointment (3 Drop Maximum: If you are having trouble matching with a tutor, contact us.)
> 
> Make an Appointment:
> Subject
> Grade Level
> Weekly Availability (To maximize your options, include all times that you can make on a weekly basis):
> 
> Student Resources:
> A collection of well formatted links with descriptions - scour
> from other sites, etc.
> 
> Tutor Page:
> 
> Login or Signup to Volunteer
> 
> Sign Up:
> Email*
> Name*
> Phone Number*
> Which of the following have you attained:* In college, college, Masters, PhD
> Do you have experience tutoring professionally:
> Yes
> No
> 
> Number of Years:* 1, 2, 3, 4, 5, +
> 
> School [Text Field]
> 
> City:
> State:
> Zip:
> 
> Hobbies:
> Hobby 1:
> Hobby 2:
> Hobby 3:
> 
> Message (tutors can add their comments) [text field]:
> 
> #Notes: Tutor bios will be automatically generated as: “Hi, my name is NAME. I am currently getting/have completed my degree in DEGREE. I am volunteering with covidtutoring.org to help students everywhere regain educational access! In my free time I enjoy ___, ____, and _./ and /
> 
> Once Logged In -->
> 
> Student Roster: Grid view (Student: First Name ?, subject, next appointment)
> 
> Calendar where tutors can block off their weekly commitments (on the half hour in their local time zones).
> 
> FAQs:
> 
> What is CovidTuotoring.org / Tutorbook … or whatever.
> 
> How you we are able to offer free support
> 
> How we ensure a quality experience
> 
> General Guidelines for Protecting your privacy online
> 
> How you are in control when using our product
> 
> How we are helping our communities

**Comment by AlephTaw** [comment]
These are the slides:

https://docs.google.com/presentation/d/1XwHQdEXl_t0JtWILfC_mwHFPewS6nKygYU8aYvwNFRc/edit#slide=id.p

**Comment by nicholaschiang** [comment]
Finished MVP, closing this issue (as it's better to be referenced as a Milestone anyways).
