### ISSUE TITLE
Issue with volunteer sign up form 

### ISSUE THREAD

**Issue by ryantzr1** [tutorbookapp/covid-tutoring#57]
![image](https://user-images.githubusercontent.com/63581031/82054234-2deccd80-96f1-11ea-8b14-aad227c0f936.png)
Not all grades can be found! 8th grade to 12th grade arent found here

**Comment by nicholaschiang** [comment]
Yes @ryantzr1 they can be found. Just type the start of the subject that you're looking to select:

![subject-selection](https://user-images.githubusercontent.com/20798889/82135869-81781d80-97bc-11ea-99c2-90c3e0b039db.gif)

9-12th grade subjects aren't listed as "12th Grade Math" however. They're instead the actual class names (e.g. "12th Grade Math" is typically "AP Calculus BC" or "AP Calculus AB").
